"""Coverage check: does a course transcript set cover the exam syllabus? Runs once per course via Opus.
Usage: py tools/narrate/coverage.py <exam> "<course folder>"  (e.g. CPMAI "Udemy - Sanal Mathew John")
Writes Transcripts/<exam>/<course folder>/COVERAGE.md and COVERAGE.json."""
import json, re, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from llm import ask, json_block

ROOT = Path(r"C:\Architect")
exam, folder = sys.argv[1], sys.argv[2]
src = ROOT / "Transcripts" / exam / folder
reg = {"CPMAI": "cpmai", "AB-100": "ab-100", "AB-620": "ab-620", "AB-410": "ab-410"}[exam]
syllabus = (ROOT / "curriculum" / "objectives" / f"{reg}.md").read_text(encoding="utf-8")

parts = []
for f in sorted(src.glob("*.txt")):
    body = re.sub(r"^# .*\n", "", f.read_text(encoding="utf-8"), flags=re.M).strip()
    parts.append(f"\n\n<<<LECTURE {f.stem}>>>\n{body}")
transcripts = "".join(parts)

SYSTEM = f"""You are auditing whether a third-party course covers an exam syllabus. You will receive the official
objective register (tasks with IDs and illustrative enablers) and the auto-generated captions of every lecture of
the course. The captions are noisy (heavy accent, mis-heard terms such as "Cpma" for CPMAI, "KPMG" for PMI); infer
the intended meaning. Be strict: a task counts as "well" covered only if the lecture actually teaches it at a
depth that would let someone answer an exam question on it; "light" if it is mentioned or partly taught; "none"
if absent. Do not be generous.

Return ONLY a ```json block with this shape:
{{
 "tasks": [ {{"id": "CPMAI-2.5", "coverage": "well|light|none", "lectures": ["004 - Introduction to CPMAI"], "note": "one line"}} ],
 "lectures": [ {{"lecture": "004 - Introduction to CPMAI", "summary": "one line", "value": "high|medium|low|fluff", "caption_quality": "ok|poor", "caption_errors": ["Cpma -> CPMAI"]}} ],
 "course_verdict": "three sentences: what the course is good for, what it is missing, whether it should be the spine or a supplement",
 "extra_topics": ["topics the course teaches that are not in the register, e.g. ML algorithm types, V7->V8 transition"]
}}
Cover every task ID in the register exactly once. Lecture list must include every lecture."""

reply = ask(SYSTEM, f"# OBJECTIVE REGISTER\n\n{syllabus}\n\n# COURSE CAPTIONS\n{transcripts}", model="opus", timeout=1500, tag=f"coverage:{exam}")
data = json_block(reply)
(src / "COVERAGE.json").write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

counts = {}
for t in data["tasks"]:
    counts[t["coverage"]] = counts.get(t["coverage"], 0) + 1
md = [f"# Coverage: {folder} vs {exam} syllabus", "", f"> Generated by tools/narrate/coverage.py (Opus) — {counts}", "",
      "## Verdict", "", data.get("course_verdict", ""), "", "## Tasks", "", "| ID | Coverage | Lectures | Note |", "|---|---|---|---|"]
for t in data["tasks"]:
    md.append(f"| {t['id']} | **{t['coverage']}** | {', '.join(t.get('lectures', []))} | {t.get('note','')} |")
md += ["", "## Lectures", "", "| Lecture | Value | Captions | Summary | Errors |", "|---|---|---|---|---|"]
for l in data["lectures"]:
    md.append(f"| {l['lecture']} | {l.get('value','')} | {l.get('caption_quality','')} | {l.get('summary','')} | {'; '.join(l.get('caption_errors', []))} |")
md += ["", "## Topics taught beyond the register", ""] + [f"- {x}" for x in data.get("extra_topics", [])]
(src / "COVERAGE.md").write_text("\n".join(md) + "\n", encoding="utf-8")
print("coverage:", counts)
