"""Build a private podcast feed (RSS 2.0 with iTunes tags) from a folder of chapter MP3s.
Usage: py tools/narrate/feed.py <folder> --base-url https://host/path/ [--title "..."] [--author "..."]
Writes <folder>/feed.xml; upload the folder (MP3s + feed.xml) to any private web location and subscribe
to the feed URL in a podcast app. MP3s are git-ignored; do not commit them."""
import argparse, datetime, html, re
from pathlib import Path

ap = argparse.ArgumentParser()
ap.add_argument("folder"); ap.add_argument("--base-url", required=True)
ap.add_argument("--title", default="Architect — CPMAI audio course")
ap.add_argument("--author", default="Architect (Warwick)")
ap.add_argument("--description", default="Narrated exam-prep course on the PMI-CPMAI syllabus, generated by the Architect programme for private study.")
a = ap.parse_args()
folder = Path(a.folder); base = a.base_url.rstrip("/") + "/"
items = []
for mp3 in sorted(folder.glob("*.mp3")):
    md = mp3.with_suffix(".md")
    title = mp3.stem
    if md.exists():
        m = re.search(r'^title:\s*"(.*)"', md.read_text(encoding="utf-8"), flags=re.M)
        if m: title = f"{mp3.stem[:2]} · {m.group(1)}"
    size = mp3.stat().st_size
    pub = datetime.datetime.fromtimestamp(mp3.stat().st_mtime, datetime.timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")
    url = base + mp3.name.replace(" ", "%20")
    items.append(f"""    <item>
      <title>{html.escape(title)}</title>
      <enclosure url="{html.escape(url)}" length="{size}" type="audio/mpeg"/>
      <guid isPermaLink="false">{html.escape(mp3.name)}</guid>
      <pubDate>{pub}</pubDate>
      <itunes:episode>{int(mp3.stem[:2]) if mp3.stem[:2].isdigit() else 0}</itunes:episode>
    </item>""")
rss = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <channel>
    <title>{html.escape(a.title)}</title>
    <link>{html.escape(base)}</link>
    <language>en-gb</language>
    <itunes:author>{html.escape(a.author)}</itunes:author>
    <itunes:block>Yes</itunes:block>
    <description>{html.escape(a.description)}</description>
{chr(10).join(items)}
  </channel>
</rss>
"""
(folder / "feed.xml").write_text(rss, encoding="utf-8")
print(f"feed.xml with {len(items)} episodes -> subscribe to {base}feed.xml")
